import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, Badge, Button } from '@/components/ui';
export default function CompletedJobsGallery({ photos, maxItems, compact, onRemove }) {
    if (!photos || photos.length === 0) {
        return (_jsx(Card, { className: "p-4 bg-white/80 border-dashed border-gray-200", children: _jsx("p", { className: "text-sm text-gray-500", children: "No completed jobs uploaded yet." }) }));
    }
    const visiblePhotos = maxItems ? photos.slice(0, maxItems) : photos;
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: `grid gap-4 ${compact ? 'md:grid-cols-1' : 'md:grid-cols-2'}`, children: visiblePhotos.map((photo) => (_jsxs(Card, { className: "p-4 space-y-3", children: [_jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-gray-900", children: "Transformation Spotlight" }), _jsxs("p", { className: "text-xs text-gray-500", children: ["Uploaded ", new Date(photo.uploadedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })] })] }), photo.servicesUsed?.length ? (_jsx(Badge, { variant: "warning", className: "capitalize", children: photo.servicesUsed[0] })) : null] }), _jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs("figure", { className: "space-y-1", children: [_jsx("p", { className: "text-xs font-semibold text-gray-500 uppercase tracking-wide", children: "Before" }), _jsx("img", { src: photo.beforeImage, alt: `Before cleaning ${photo.id}`, className: "w-full h-32 md:h-40 object-cover rounded-xl border border-gray-100" })] }), _jsxs("figure", { className: "space-y-1", children: [_jsx("p", { className: "text-xs font-semibold text-emerald-600 uppercase tracking-wide", children: "After" }), _jsx("img", { src: photo.afterImage, alt: `After cleaning ${photo.id}`, className: "w-full h-32 md:h-40 object-cover rounded-xl border border-emerald-100" })] })] }), photo.description && (_jsx("p", { className: "text-sm text-gray-600", children: photo.description })), _jsxs("div", { className: "flex items-center justify-between text-xs text-gray-500", children: [_jsxs("span", { children: ["By ", photo.uploadedBy] }), photo.servicesUsed && photo.servicesUsed.length > 1 && (_jsxs("span", { children: [photo.servicesUsed.length, " services"] }))] }), onRemove && (_jsx(Button, { variant: "outline", size: "sm", className: "w-full", onClick: () => onRemove(photo.id), children: "Remove from gallery" }))] }, photo.id))) }), maxItems && photos.length > maxItems && (_jsxs("p", { className: "text-xs text-gray-500 text-right", children: ["+ ", photos.length - maxItems, " more showcased jobs"] }))] }));
}
